version: "3.3"
services:
  gateway:
    container_name: gateway
    restart: unless-stopped
    image: gateway
    build: .
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:80"
networks:
  default:
    external:
      name: kavianex
