version: '3.3'
services:
  apigateway-service:
    container_name: apigateway-service
    restart: unless-stopped
    image: apigateway-service
    build: .
    environment:
      - SERVICE_PORT=80
    ports:
      - "8000:80"
